### ISSUE TITLE
error with firebase-analytics dependency version

### ISSUE THREAD

**Issue by christoribeiro** [chemerisuk/cordova-plugin-firebase-authentication#3]
Hi @chemerisuk, i tried to install `cordova-plugin-firebase-authentication` but got this error:

```

Installing "cordova-plugin-firebase-authentication" for ios
        Failed to install 'cordova-plugin-firebase-authentication': Error
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:581:33
             at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
             at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
             at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
             at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
             at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
             at _combinedTickCallback (internal/process/next_tick.js:131:7)
             at process._tickCallback (internal/process/next_tick.js:180:9)
        Error: Version of installed plugin: "cordova-plugin-firebase-analytics@0.11.0" does not satisfy dependency
        plugin requirement "cordova-plugin-firebase-analytics@~0.10.0". Try --force to use installed plugin as
        dependency.
```

**Comment by chemerisuk** [comment]
use version 0.11.1

**Comment by christoribeiro** [comment]
You may forgot a `npm publish`. On npmjs.com the last release is `0.10.1`.

**Comment by chemerisuk** [comment]
Done, thank you
